using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using SourceGenerator;
using System.Text;

namespace TestApp;

internal class SourceGeneratorTests
{
    [Test]
    public async Task Execute_Generates_File()
    {
        var harness = new CSharpSourceGeneratorTest<FileGenerator, DefaultVerifier>();

        var embeddedAttribute = SourceText.From("""
            // <auto-generated/>
            namespace Microsoft.CodeAnalysis
            {
                internal sealed partial class EmbeddedAttribute : global::System.Attribute
                {
                }
            }
            """, Encoding.UTF8);

        var expected = SourceText.From("""
            using System;
            
            namespace SourceGenerator
            {
                public class GeneratedClass
                {
            
                }
            }
            """,
            Encoding.UTF8);
        harness.TestState.GeneratedSources.Add((@"SourceGenerator\SourceGenerator.FileGenerator\Microsoft.CodeAnalysis.EmbeddedAttribute.cs", embeddedAttribute));
        harness.TestState.GeneratedSources.Add((@"SourceGenerator\SourceGenerator.FileGenerator\GeneratedClass.g.cs", expected));        
        await harness.RunAsync();
    }
}